version: '3.4'

services:

  app:
    build:
      dockerfile: build/Dockerfile
      context: .
    hostname: robocode
    network_mode: host
    environment: 
      - DISPLAY=${ROBOCODE-LOCAL-IP}:0
    volumes: 
      - ./shared:/root/share/robocode/1.9.3.7
    command: robocode