version: '3.4'

services:

  app:
    build:
      dockerfile: build/Dockerfile
      context: .
    hostname: robocode
    network_mode: host
    environment: 
      - DISPLAY=${ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'}:0
    volumes: 
      - shared:/root/share/robocode/1.9.3.7
    command: robocode