version: '3.4'

services:
  app:
    build:
      dockerfile: build/Dockerfile
      context: .
    hostname: robocode
    network_mode: host
    environment: 
      - DISPLAY=${ROBOCODE_LOCAL_IP}:0
    volumes: 
      - ./share:/root/.local/share
    command: robocode